---
version: 3
images:
  base_image:
    name: quay.io/rockylinux/rockylinux:9
dependencies:
  ansible_core:
    package_pip: ansible-core<2.17
  ansible_runner:
    package_pip: ansible-runner
  galaxy: build/requirements-inventory.yml
  python: build/requirements.txt
  system: build/bindep-3.11.txt
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  prepend_builder:
    - RUN dnf install -y epel-release
  prepend_final:
    - RUN dnf install -y epel-release
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - ADD certs /etc/pki/ca-trust/source/anchors
    - RUN update-ca-trust
    - RUN git lfs install --system
